name: Deploy Docs to GitHub Pages
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    workflow_dispatch:
  
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
    build:
        name: Build and Deploy to Pages
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        permissions:
          contents: read
          pages: write
          id-token: write

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Build Clay 
          run: curl https://raw.githubusercontent.com/clay-doc/clay-oven/refs/heads/main/run-oven.sh | sh
          env:
            CLAY_FONTAWESOME_KIT: ${{ secrets.CLAY_FONTAWESOME_KIT }}

        - name: Setup Pages
          uses: actions/configure-pages@v3

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: './publish/public'
    
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}